theme: jekyll-theme-minimal
title: [Boise State ADaPT Lab]
description: [Application Data flow optimizations with Programming languages and Transformations Lab at Boise State University]

logo: [./images/adapt-logo.png]
show_downloads: ["false"]
